input_path: artifacts/chemquests_hf_db/full_text.jsonl
output_path: artifacts/tests/jinaai_jina_embeddings_v2_base_en_fixed_token_c448_o64/chunks/chunks.jsonl
text_field: text
id_field: corpus_id
token_count_encoding: cl100k_base
token_count_model: null
compute_offsets: true
max_docs: null
strategy:
  name: fixed_token
  params:
    model_name: jinaai/jina-embeddings-v2-base-en
    chunk_size: 448
    chunk_overlap: 64
    add_start_index: false
    strip_whitespace: true
