input_path: artifacts2/chemquests/full_text.jsonl
output_path: artifacts2/chunks/chunks.jsonl
text_field: text
id_field: corpus_id
token_count_encoding: cl100k_base
token_count_model: null
compute_offsets: true
max_docs: null
strategy:
  name: recursive_token
  params:
    chunk_size: 800
    chunk_overlap: 100
    separators:
    - '\n\n'
    - '\n'
    - .
    - '?'
    - '!'
    - ' '
    - ''
    keep_separator: true
    is_separator_regex: false
